// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoaeB2A41Dbyp7tQ-0gArvxfeUo3j5V0A',
    appId: '1:122127433843:web:34f22764706ed8cd4aaa06',
    messagingSenderId: '122127433843',
    projectId: 'bhoj-b0892',
    authDomain: 'bhoj-b0892.firebaseapp.com',
    storageBucket: 'bhoj-b0892.appspot.com',
    measurementId: 'G-9XQ24E2CVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC62yMWd7SQQ5kTd-iLoWqT2_gPiPV_1t8',
    appId: '1:122127433843:android:168bdf9c80471c874aaa06',
    messagingSenderId: '122127433843',
    projectId: 'bhoj-b0892',
    storageBucket: 'bhoj-b0892.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMTBdfCreZKHkrAQFNwnfyYwyrBF7b6v4',
    appId: '1:122127433843:ios:3437e0e812c6f3394aaa06',
    messagingSenderId: '122127433843',
    projectId: 'bhoj-b0892',
    storageBucket: 'bhoj-b0892.appspot.com',
    iosBundleId: 'com.example.bhoj1',
  );
}
